deployment:
  tasks:
    - export DEPLOYPATH=/home/himala11/trek
    - /bin/cp -r accounts $DEPLOYPATH
    - /bin/cp -r accountsmanagement $DEPLOYPATH
    - /bin/cp -r blog $DEPLOYPATH
    - /bin/cp -r booking $DEPLOYPATH
    - /bin/cp -r holiday $DEPLOYPATH
    - /bin/cp -r managements $DEPLOYPATH
    - /bin/cp -r payment $DEPLOYPATH
    - /bin/cp -r queries $DEPLOYPATH
    - /bin/cp -r questionanswer $DEPLOYPATH
    - /bin/cp -r report $DEPLOYPATH
    - /bin/cp -r services $DEPLOYPATH
    - /bin/cp -r testonomial $DEPLOYPATH
    - /bin/cp -r static $DEPLOYPATH
