# Generated by Django 4.2.6 on 2024-08-07 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destination', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='activity_images/')),
                ('destinations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='destination.destination')),
            ],
        ),
    ]
