# Generated by Django 4.2.6 on 2024-09-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destination', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to='activity_images/')),
                ('destinations_activities', models.ManyToManyField(related_name='activities', to='destination.destination')),
            ],
        ),
    ]
