# Generated by Django 4.2.6 on 2024-08-07 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0001_initial'),
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='destinations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='destination.destination'),
        ),
    ]
