# Generated by Django 4.2.6 on 2024-08-11 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='destinations',
        ),
    ]
