# Generated by Django 4.2.6 on 2024-08-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_rename_destinations_activity_destinations_activities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=models.ImageField(null=True, upload_to='activity_images/'),
        ),
    ]
