# Generated by Django 4.2.6 on 2024-08-27 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0002_alter_destination_featured_image_and_more'),
        ('activities', '0003_alter_activity_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='destinations_activities',
            field=models.ManyToManyField(related_name='activities', to='destination.destination'),
        ),
    ]
