# Generated by Django 4.2.6 on 2024-08-09 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.FloatField()),
                ('payment_mode', models.CharField(choices=[('khalti', 'Khalti'), ('esewa', 'Esewa'), ('cod', 'Cash On Ddelivery')], max_length=100)),
                ('refrence_id', models.CharField(max_length=4000, unique=True)),
                ('remarks', models.CharField(blank=True, max_length=3000, null=True)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Paid'), ('half', 'Half Payment'), ('cod', 'Cash On Delivery'), ('refunded', 'Refunded')], max_length=255)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='booking.servicebook')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentFail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_mode', models.CharField(choices=[('khalti', 'Khalti'), ('esewa', 'Esewa'), ('cod', 'Cash On Ddelivery')], max_length=100)),
                ('refrence_id', models.CharField(max_length=4000)),
                ('services_product', models.CharField(max_length=100)),
                ('server_response', models.CharField(blank=True, max_length=3000, null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_fail', to='booking.holidaytripbook')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.FloatField()),
                ('payment_mode', models.CharField(choices=[('khalti', 'Khalti'), ('esewa', 'Esewa'), ('cod', 'Cash On Ddelivery')], max_length=100)),
                ('refrence_id', models.CharField(max_length=4000, unique=True)),
                ('remarks', models.CharField(blank=True, max_length=3000, null=True)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Paid'), ('half', 'Half Payment'), ('cod', 'Cash On Delivery'), ('refunded', 'Refunded')], max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='booking.holidaytripbook')),
            ],
        ),
    ]
