# Generated by Django 4.2.6 on 2024-08-09 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destination_list', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('destinations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='destination_list.destination_list')),
            ],
        ),
    ]
