# Generated by Django 4.2.6 on 2024-08-15 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='destinations',
            new_name='destination_collection',
        ),
    ]
