# Generated by Django 4.2.6 on 2024-08-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0005_remove_destination_activities_and_more'),
        ('collection', '0002_remove_collection_destinations'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='destinations',
            field=models.ManyToManyField(to='destination.destination'),
        ),
    ]
