# Generated by Django 4.2.6 on 2024-08-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_rename_destinations_collection_destination_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='activity_images/'),
        ),
    ]
