# Generated by Django 4.2.6 on 2024-08-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_remove_collection_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='index',
            field=models.PositiveIntegerField(default=999),
        ),
    ]
