# Generated by Django 4.2.6 on 2024-08-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0002_alter_destination_featured_image_and_more'),
        ('collection', '0005_collection_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='destination_collection',
            field=models.ManyToManyField(related_name='collections', to='destination.destination'),
        ),
    ]
