# Generated by Django 4.2.6 on 2024-08-23 05:15

import accounts.utilities.model_utils
import accounts.utilities.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=accounts.utilities.model_utils.LowercaseEmailField(blank=True, error_messages={'unique': 'Given Email has already been registered.'}, max_length=254, null=True, unique=True, validators=[accounts.utilities.validators.validate_emails], verbose_name='email address'),
        ),
    ]
