# Generated by Django 4.2.6 on 2024-08-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upcoming_departure_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('upcoming_departure_status', models.BooleanField(blank=True, default=False, null=True)),
                ('upcoming_departure_price', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
