# Generated by Django 4.2.6 on 2024-08-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departure', '0002_alter_departure_upcoming_departure_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departure',
            name='upcoming_departure_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
