# Generated by Django 4.2.6 on 2024-08-09 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0007_remove_holidaytrip_activities_and_more'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidaytripbook',
            name='holiday_trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_trip_book', to='holiday.destination'),
        ),
    ]
