# Generated by Django 4.2.6 on 2024-08-11 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0001_initial'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinationbook',
            name='airlines',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airlines_booking', to='airlines.airlines'),
        ),
    ]
