# Generated by Django 4.2.6 on 2024-08-20 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_destinationbook_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destinationbook',
            old_name='number_of_travellers',
            new_name='number_of_travelers',
        ),
    ]
