# Generated by Django 4.2.6 on 2024-08-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_rename_number_of_travellers_destinationbook_number_of_travelers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinationbook',
            name='airlines',
            field=models.CharField(max_length=450),
        ),
    ]
