# Generated by Django 4.2.6 on 2024-09-16 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activity_description'),
        ('destination', '0005_package_description'),
        ('booking', '0003_alter_destinationbook_customize_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinationbook',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_booking', to='activities.activity'),
        ),
        migrations.AlterField(
            model_name='destinationbook',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_booking', to='destination.package'),
        ),
    ]
