# Generated by Django 4.2.6 on 2024-08-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_destinationbook_airlines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinationbook',
            name='user',
        ),
        migrations.AddField(
            model_name='destinationbook',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='destinationbook',
            name='full_name',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='destinationbook',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
