# Generated by Django 4.2.6 on 2024-08-30 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_destinationbook_user_destinationbook_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinationbook',
            name='airlines',
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
    ]
