# Generated by Django 4.2.6 on 2024-09-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_destinationbook_airlines'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationbook',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
