# Generated by Django 4.2.6 on 2024-09-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_destinationbook_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinationbook',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
