# Generated by Django 4.2.6 on 2024-08-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='read_time',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
