# Generated by Django 4.2.6 on 2024-08-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_is_popular_blog_read_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='read_time',
            field=models.CharField(default='10 mins', max_length=150),
        ),
    ]
