# Generated by Django 4.2.6 on 2024-09-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_meta_description_blog_meta_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(unique=True),
        ),
    ]
