# Generated by Django 4.2.6 on 2024-08-11 09:32

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=150)),
                ('star_rating', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('review_description', models.TextField(blank=True, default='')),
                ('add_image', models.ImageField(blank=True, null=True, upload_to='review/images')),
            ],
        ),
    ]
