# Generated by Django 4.2.6 on 2024-08-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_review_created_date_review_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
