# Generated by Django 4.2.6 on 2024-08-22 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_review_show'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='show',
            new_name='is_show',
        ),
    ]
