# Generated by Django 4.2.6 on 2024-09-01 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0006_alter_destination_meta_description_and_more'),
        ('review', '0006_alter_review_star_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_review', to='destination.destination'),
        ),
    ]
