# Generated by Django 4.2.6 on 2024-08-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='destination/featured/images/'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='trip_map_image',
            field=models.ImageField(blank=True, null=True, upload_to='destination/trip-map/images/'),
        ),
    ]
