# Generated by Django 4.2.6 on 2024-09-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='overview',
            field=models.CharField(blank=True, null=True),
        ),
    ]
