# Generated by Django 4.2.6 on 2024-08-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destinationgalleryimages',
            old_name='holiday_trip',
            new_name='destination_trip',
        ),
        migrations.RenameField(
            model_name='destinationreview',
            old_name='holiday_trip',
            new_name='destination_trip',
        ),
        migrations.AlterField(
            model_name='destination',
            name='trip_map_image',
            field=models.ImageField(blank=True, null=True, upload_to='destination/trip-map/images/'),
        ),
        migrations.AlterField(
            model_name='destinationgalleryimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='destination/images/'),
        ),
        migrations.AlterField(
            model_name='package',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='destination/destination_type_image/'),
        ),
    ]
