# Generated by Django 4.2.6 on 2024-08-11 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0002_rename_holiday_trip_destinationgalleryimages_destination_trip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='gallery_images',
        ),
    ]
