# Generated by Django 4.2.6 on 2024-08-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0002_alter_destination_featured_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='accommodation',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='destination',
            name='best_season',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='destination_title',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='destination',
            name='max_altitude',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='destination',
            name='meals',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='destination',
            name='nature_of_trip',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='destination',
            name='trip_grade',
            field=models.CharField(max_length=150),
        ),
    ]
