# Generated by Django 4.2.6 on 2024-08-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0003_alter_destination_accommodation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='group_size',
            field=models.CharField(max_length=70),
        ),
    ]
