# Generated by Django 4.2.6 on 2024-08-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0003_remove_destination_gallery_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='select_packages',
        ),
        migrations.AddField(
            model_name='destination',
            name='packages',
            field=models.ManyToManyField(to='destination.package'),
        ),
        migrations.AddField(
            model_name='destination',
            name='price_type',
            field=models.CharField(default='NPR', max_length=3),
        ),
    ]
