# Generated by Django 4.2.6 on 2024-09-10 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0003_destination_created_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='duration',
            field=models.CharField(blank=True, null=True),
        ),
    ]
