# Generated by Django 4.2.6 on 2024-08-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0004_alter_destination_group_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='meta_description',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='meta_keywords',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='meta_title',
            field=models.CharField(blank=True, editable=False, max_length=150, null=True),
        ),
    ]
