# Generated by Django 4.2.6 on 2024-08-11 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0004_remove_destination_select_packages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='collection',
        ),
    ]
