# Generated by Django 4.2.6 on 2024-08-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0005_destination_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='meta_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
