# Generated by Django 4.2.6 on 2024-08-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0006_destination_is_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='description',
        ),
        migrations.AlterField(
            model_name='package',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='destination/package_image/'),
        ),
    ]
