# Generated by Django 4.2.6 on 2024-09-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0006_alter_destination_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='price_type',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
