# Generated by Django 4.2.6 on 2024-08-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0007_remove_package_description_alter_package_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='featured_image',
            field=models.ImageField(upload_to='destination/featured/images/'),
        ),
    ]
