# Generated by Django 4.2.6 on 2024-09-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0007_alter_destination_price_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='destination_title',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
