# Generated by Django 4.2.6 on 2024-08-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0008_alter_destination_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='trip_map_image',
            field=models.ImageField(upload_to='destination/trip-map/images/'),
        ),
    ]
