# Generated by Django 4.2.6 on 2024-08-20 06:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airlines',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airlines',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
