# Generated by Django 4.2.6 on 2024-08-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('top', 'Top'), ('middle', 'Middle'), ('bottom', 'Bottom')], max_length=23)),
                ('video', models.FileField(blank=True, null=True, upload_to='hero_section_videos')),
                ('video_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
