# Generated by Django 4.2.6 on 2024-08-27 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queries',
            name='user',
        ),
        migrations.AddField(
            model_name='queries',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='queries',
            name='phone',
            field=models.CharField(default='', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='queries',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='queries',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='queries',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
