# Generated by Django 4.2.6 on 2024-09-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0002_remove_queries_user_queries_name_queries_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='queries',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
