# Generated by Django 4.2.6 on 2024-09-09 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_popup_created_date_time_alter_popup_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popup',
            name='title',
            field=models.CharField(null=True),
        ),
    ]
