# Generated by Django 4.2.6 on 2024-08-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_herosection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='company/hero_section_videos'),
        ),
    ]
