# Generated by Django 4.2.6 on 2024-09-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_popup_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popup',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
