# Generated by Django 4.2.6 on 2024-09-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_popup_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSectionOverlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overlay_text', models.CharField(blank=True, max_length=200, null=True)),
                ('button_text', models.CharField(blank=True, max_length=200, null=True)),
                ('button_link', models.URLField(blank=True, null=True)),
                ('is_button', models.BooleanField(default=False)),
                ('is_overlay_text', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='is_button',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='is_title',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='title',
        ),
    ]
