# Generated by Django 4.2.6 on 2024-08-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_remove_legaldocuments_user_herosection_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legaldocuments',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='components/legal-documents'),
        ),
        migrations.AlterField(
            model_name='meetteam',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='components/meetteam'),
        ),
    ]
