# Generated by Django 4.2.6 on 2024-09-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_legaldocuments_image_alter_meetteam_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='is_button',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='herosection',
            name='is_title',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
