# Generated by Django 4.2.6 on 2024-09-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_aboutus_termandcondition_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetteam',
            name='index',
            field=models.PositiveIntegerField(default=999),
        ),
    ]
