# Generated by Django 4.2.6 on 2024-09-12 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_meetteam_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSectionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_text', models.CharField(blank=True, max_length=200, null=True)),
                ('stat_number', models.CharField(blank=True, max_length=200, null=True)),
                ('stat_description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
