# Generated by Django 4.2.6 on 2024-09-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faqs',
            old_name='updated_at',
            new_name='updated_date',
        ),
        migrations.RemoveField(
            model_name='faqs',
            name='created_at',
        ),
        migrations.AddField(
            model_name='faqs',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='faqs',
            name='created_date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
