# Generated by Django 4.2.6 on 2024-08-09 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0007_remove_holidaytrip_activities_and_more'),
        ('faqs', '0002_faqs_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqs',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs_for_destination', to='holiday.destination'),
        ),
        migrations.AddField(
            model_name='faqs',
            name='faq_type',
            field=models.CharField(choices=[('company', 'Company'), ('destination', 'Destination')], default='company', max_length=11),
        ),
        migrations.AddField(
            model_name='faqs',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
