# Generated by Django 4.2.6 on 2024-08-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidaytrip',
            name='others_description',
            field=models.TextField(blank='', default='', null=True),
        ),
    ]
