# Generated by Django 4.2.6 on 2024-08-07 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0001_initial'),
        ('holiday', '0002_holidaytrip_others_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HolidayTripHaveImages',
            new_name='HolidayTripGalleryImages',
        ),
        migrations.RenameField(
            model_name='holidaytrip',
            old_name='day_stay',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='holidaytrip',
            old_name='image',
            new_name='featured_image',
        ),
        migrations.RenameField(
            model_name='holidaytrip',
            old_name='night_stay',
            new_name='group_size',
        ),
        migrations.RenameField(
            model_name='holidaytrip',
            old_name='holiday_type',
            new_name='packages',
        ),
        migrations.RenameField(
            model_name='holidaytrip',
            old_name='map',
            new_name='trip_map_url',
        ),
        migrations.RenameField(
            model_name='holidaytripgalleryimages',
            old_name='holiday_destination',
            new_name='holiday_trip',
        ),
        migrations.RemoveField(
            model_name='holidaytrip',
            name='best_seasosn',
        ),
        migrations.RemoveField(
            model_name='holidaytrip',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='holidaytrip',
            name='person',
        ),
        migrations.AddField(
            model_name='holidaytrip',
            name='best_season',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='holidaytrip',
            name='faqs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='faqs.faqs'),
        ),
        migrations.AddField(
            model_name='holidaytrip',
            name='gear_and_equipment',
            field=models.TextField(blank='', default='', null=True),
        ),
        migrations.AddField(
            model_name='holidaytrip',
            name='inclusion_and_exclusion',
            field=models.TextField(blank='', default='', null=True),
        ),
        migrations.AddField(
            model_name='holidaytrip',
            name='overview',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='holidaytrip',
            name='trip_map_image',
            field=models.ImageField(blank=True, null=True, upload_to='holiday/trip-map/images/'),
        ),
        migrations.AddField(
            model_name='holidaytrip',
            name='upcoming_departure_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='holidaytrip',
            name='upcoming_departure_price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='holidaytrip',
            name='upcoming_departure_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='holidaytrip',
            name='useful_information',
            field=models.TextField(blank='', default='', null=True),
        ),
    ]
