# Generated by Django 4.2.6 on 2024-08-07 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
        ('activities', '0002_alter_activity_destinations'),
        ('holiday', '0003_rename_holidaytriphaveimages_holidaytripgalleryimages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidaytrip',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection.collection'),
        ),
        migrations.AlterField(
            model_name='holidaytrip',
            name='activities',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.activity'),
        ),
    ]
