# Generated by Django 4.2.6 on 2024-08-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departure', '0001_initial'),
        ('holiday', '0005_remove_holidaytrip_faqs_holidaytrip_faqs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holidaytrip',
            name='upcoming_departure_date',
        ),
        migrations.RemoveField(
            model_name='holidaytrip',
            name='upcoming_departure_price',
        ),
        migrations.RemoveField(
            model_name='holidaytrip',
            name='upcoming_departure_status',
        ),
        migrations.AddField(
            model_name='holidaytrip',
            name='departure',
            field=models.ManyToManyField(to='departure.departure'),
        ),
    ]
