# Generated by Django 4.2.6 on 2024-08-09 06:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
        ('activities', '0002_alter_activity_destinations'),
        ('departure', '0001_initial'),
        ('faqs', '0002_faqs_created_at'),
        ('holiday', '0006_remove_holidaytrip_upcoming_departure_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holidaytrip',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='holidaytrip',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='holidaytrip',
            name='departure',
        ),
        migrations.RemoveField(
            model_name='holidaytrip',
            name='faqs',
        ),
        migrations.RemoveField(
            model_name='holidaytrip',
            name='packages',
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=450)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=450, null=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='holiday/featured/images/')),
                ('important_points', models.CharField(max_length=450)),
                ('stay_type', models.CharField(max_length=450)),
                ('duration_stay', models.IntegerField()),
                ('description', models.TextField()),
                ('trip_map_url', models.URLField(blank=True, null=True)),
                ('trip_map_image', models.ImageField(blank=True, null=True, upload_to='holiday/trip-map/images/')),
                ('trip_information', models.CharField(max_length=450)),
                ('nature_of_trip', models.CharField(max_length=450)),
                ('others_description', models.TextField(blank=True, default='', null=True)),
                ('others', models.CharField(max_length=450)),
                ('trip_grade', models.CharField(max_length=450)),
                ('max_altitude', models.CharField(max_length=450)),
                ('group_size', models.PositiveIntegerField()),
                ('duration', models.PositiveIntegerField()),
                ('accomodation', models.CharField(max_length=450)),
                ('meals', models.CharField(max_length=5000)),
                ('best_season', models.CharField(blank=True, max_length=3000, null=True)),
                ('inclusion_and_exclusion', models.TextField(blank=True, default='', null=True)),
                ('overview', models.CharField(blank=True, max_length=5000, null=True)),
                ('ltinerary', models.TextField()),
                ('weather', models.CharField(max_length=450)),
                ('gear_and_equipment', models.TextField(blank=True, default='', null=True)),
                ('useful_information', models.TextField(blank=True, default='', null=True)),
                ('is_price', models.BooleanField(default=False)),
                ('price', models.PositiveIntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('activities', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.activity')),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection.collection')),
                ('departures', models.ManyToManyField(related_name='destination_departures', to='departure.departure')),
                ('faqss', models.ManyToManyField(related_name='destination_faqs', to='faqs.faqs')),
                ('images', models.ManyToManyField(related_name='destination_images', to='holiday.holidaytripgalleryimages')),
                ('packages', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='holiday.holidaytype')),
            ],
        ),
        migrations.AlterField(
            model_name='holidaytripgalleryimages',
            name='holiday_trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleryimages', to='holiday.destination'),
        ),
        migrations.AlterField(
            model_name='holidaytripreview',
            name='holiday_trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='holiday.destination'),
        ),
    ]
