# Generated by Django 4.2.6 on 2024-08-09 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0007_remove_holidaytrip_activities_and_more'),
        ('booking', '0002_alter_holidaytripbook_holiday_trip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HolidayTrip',
        ),
    ]
